### ISSUE TITLE
Error: Cannot find module 'perfectionist'

### ISSUE THREAD

**Issue by webkernel** [jbub/ghostwriter#71]
Hi,

This is the output of my _yarn run watch_ command:

yarn run v1.17.3
$ webpack --progress --colors --watch
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'perfectionist'
Require stack:
- /Users/paulopinto/hugo/paulopinto.xyz/themes/ghostwiter/webpack.config.js
- /Users/paulopinto/hugo/paulopinto.xyz/themes/ghostwiter/node_modules/webpack/bin/convert-argv.js
- /Users/paulopinto/hugo/paulopinto.xyz/themes/ghostwiter/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Users/paulopinto/hugo/paulopinto.xyz/themes/ghostwiter/webpack.config.js:2:23)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/paulopinto/hugo/paulopinto.xyz/themes/ghostwiter/webpack.config.js',
    '/Users/paulopinto/hugo/paulopinto.xyz/themes/ghostwiter/node_modules/webpack/bin/convert-argv.js',
    '/Users/paulopinto/hugo/paulopinto.xyz/themes/ghostwiter/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jbub** [comment]
Hello, did you run `yarn` before ? This is the output for me:

```
$ yarn
yarn install v1.17.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.46s.
```

```
$ yarn run watch
yarn run v1.17.3
$ webpack --progress --colors --watch
  0% compiling
Webpack is watching the files…

Hash: 1c82cd3bae8455af62f3
Version: webpack 3.12.0
Time: 724ms
     Asset     Size  Chunks             Chunk Names
styles.css  13.8 kB    0, 0  [emitted]  styles, styles
   [0] ./static/styles/index.scss 41 bytes {0} [built]
   [1] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./static/styles/index.scss 14 kB [built]
   [4] ./node_modules/css-loader!./static/styles/highlight.css 1.17 kB [built]
    + 4 hidden modules
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!static/styles/index.scss:
       [1] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./static/styles/index.scss 14 kB {0} [built]
       [3] ./node_modules/css-loader!./static/styles/highlight.css 1.17 kB {0} [built]
        + 2 hidden modules
```

**Comment by webkernel** [comment]
Hi,
Thanks for the reply. I followed the instructions on README.md and I didn't run yarn before. I just installed yarn and did:

hugo server
yarn run watch
